language: generic
services:
  - docker
before_install:
  - docker build -t weylandxlcrb/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true weylandxlcrb/react-test npm test
after_success:
  - docker build -t weylandxlcrb/multi-client ./client
  - docker build -t weylandxlcrb/multi-nginx ./nginx
  - docker build -t weylandxlcrb/multi-server ./server
  - docker build -t weylandxlcrb/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push weylandxlcrb/multi-client
  - docker push weylandxlcrb/multi-nginx
  - docker push weylandxlcrb/multi-server
  - docker push weylandxlcrb/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket: elasticbeanstalk-us-east-2-800776018205
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY